spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/click_uz_history
    username: postgres
    password: ismoil_0709
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: click-uz-reports
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8741/eureka

