spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/click_uz_history
    username: postgres
    password: 1427
  jpa:
    hibernate:
      ddl-auto: update

